### PR TITLE
Add L2 norm

### PR DESCRIPTION
**Pull request by pommedeterresautee**
For now we have no direct access to the vectors.
Simpler option is to add an option to get norm vec when requested.
https://github.com/salestock/fastText.py/issues/14

When vec will be in numpy format, will be easier to manipulate...

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
Remaining error is on Python 2.6:
```
AttributeError: 'TestSkipgramModel' object has no attribute 'assertGreater'
```
It s about the test framework and not my code.
I can fix it but do you want to be compliant with Python 2.6?

**Comment by pyk** [comment]
@pommedeterresautee thanks! 

Actually we can replace `assertGreater` with `assertTrue` like the following:

```python
self.assertTrue(value_a > value_b)
```

**Comment by pyk** [comment]
Just pushed new version to the master. So many changes over there, I will pull your branch locally and fixed it 👍

**Comment by pommedeterresautee** [comment]
Ok, just FYI, have you plan to extract the vectors from the C part and load it as a numpy matrix. Will be required for more advanced functions like similarity search...

**Comment by pyk** [comment]
@pommedeterresautee noted 🙇

**Comment by pyk** [comment]
Oh ya, all functionality of `fasttext(1)` are covered. it's time to also support Numpy matrix as the input (training set), not just a path to the file, and the word vector should be an Numpy array instead of list of float.

**Comment by pommedeterresautee** [comment]
Yeah, providing an iterator for training instead of a path would be awesome.

**Pull request closed without merging**
