### PR TITLE
Fix C++ code compilation problem on OSX

### PR DESCRIPTION
**Pull request by xiamx**
Hi @pyk could you test if the build still works on a Linux machine?

Thanks!

### CODE REVIEW

**Comment by pyk** [comment]
Thanks @xiamx , it seems the build was failed on Linux 

```
cc1plus: error: unrecognized command line option ‘-mmacosx-version-min=10.7’
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
cc1plus: error: unrecognized command line option ‘-stdlib=libc++’
error: command 'gcc' failed with exit status 1
make: *** [install] Error 1
```

https://travis-ci.org/salestock/fastText.py/jobs/155094093#L228

**Comment by pyk** [comment]
@xiamx btw, please also bump `fasttext/VERSION` to `v0.7.3` yah

**Comment by pyk** [comment]
@xiamx ahh nevermind, I will bump the version after merge this and sync the fastText library

**Comment by xiamx** [comment]
Great :) Looks like it's building fine now.

**Comment by pyk** [comment]
thanks @xiamx !

**Comment by xiamx** [comment]
My pleasure, that was a fast PR 👍

**Pull request merged**
